# Tratamento de erros
Nessa pasta cont√©m meus estudos sobre o tratamento de erros, em seu conte√∫do a cria√ß√£o de exce√ß√µes personalidas tanto n√£o verificadas, como verificadas.

# üìåTipos de erros:
### 1. Error em tempo de compila√ß√£o:
-  Impedi o processo natural da cria√ß√£o do codigo-fonte(.java) para bytecode(.class)
- Ocorre quando o codigo viola alguma regra da linguagem java(sintaxe)
- √à identificado pelo programa durante sua compila√ß√£o, antes da execu√ß√£o do programa.

### 2. Error em tempo de execu√ß√£o:
- s√£o erros que ocorrem durante a execu√ß√£o do programa
- √à causada por uma opera√ß√£o ilegal durante a execu√ß√£o do programa, como tentantiva de acessar um index invalido ou divis√£o por 0, entre outros...
- Representado pela classe Throwable, que cont√©m 2 subclasses: Error e Exception
    1. Error:
        - S√£o erros mais graves, capturados durante a execu√ß√£o do programa
        - Em sua grande maioria, esse tipo de error n√£o pode ser lidados, como falta de memoria.
    2. Exception:
       - S√£o erros excepcionais, onde o programa captura
       - Podendo ser uma exce√ß√£o verificada, onde o programa deve tratar ou uma exce√ß√£o n√£o verificada onde n√£o obrigatorio o tratamento


# üìå Exce√ß√µes Checadas e N√£o Checadas
### 1. Checadas:
- Precisa ser declarada com o throws.
- Caso ocorra, o bloco responsavel precisa ser tratado com o try/catch ou o metodo precisa conter a assinatura da clasula throws para especificar o error.
- Geralmente √© a classe Exception e suas subclasses, exceto RuntimeException e suas subclasses.

### 2. N√£o Checadas:
- N√£o precisa ser declarada com o throws.
- N√£o √© obrigat√≥rio o tratamento da exce√ß√£o.
- Geralmente √© a classe RuntimeException e suas subclasses

# üìåTry/Catch:
- Usando para o tratamento de erros que s√£o lan√ßados.
- o Bloco try corresponde a parte do codigo que o programa tentar√° executar.
- No bloco catch tratamos o error com uma exception mais generica ou mais especifica, o bloco de codigo ser√° executado caso a exce√ß√£o tratada seja lan√ßada.
```java
// Tratamento de uma exce√ß√£o de forma mais generica
// entrara no catch com qualquer error lan√ßado em tempo de execu√ß√£o.
try {
    int valor = 7 / 0;
    System.out.println(valor);
}catch (Exception e) {
    System.out.println("Ocorreu um error");
}
```
```java
// Tratamento de uma exce√ß√£o de forma mais especifica, so entrara no catch
// caso a exce√ß√£o lan√ßada seja um ArithmeticException.
try {
    int valor = 7 / 0;
    System.out.println(valor);
}catch (ArithmeticException e) {
    System.out.println("O programa teve um problema de exce√ß√£o aritmetica.");
}
```
# üìå Finally:
- Faz parte do try/catch, porem n√£o obrigatorio o uso
- Responsavel por executar algo ao final da finaliza√ß√£o do try/catch, independente de ter tido uma exce√ß√£o lan√ßada ou n√£o
```java
// Embora n√£o seja lan√ßado nenhuma exce√ß√£o no codigo
// ao final sera imprimido o System.out.println do finally.
try {
    int valor = 7 / 7;
    System.out.println(valor);
}catch (ArithmeticException e) {
    System.out.println("O programa teve um problema de exce√ß√£o aritmetica.");
}finally{
    System.out.println("O bloco try/catch finalizou!");    
}
```

# üìå Exce√ß√µes Personalizadas:
- √à possivel a cria√ß√£o de exce√ß√µes personalizadas para casos de usos diferentes
- Para lan√ßar uma exce√ß√£o personalizada podemos utilizar ```throw new StringVaziaException("nome")```
- A palavra-chave throw √© responsavel por informar que estamos lan√ßado a exce√ß√£o
```java
// Esse exception ser√° responsavel por ser lan√ßado, caso tenha uma string vazia
public class StringVaziaException extends RuntimeException{

    private String nomeDoAtributo;

    public StringVaziaException(String nomeDoAtributo) {
        this.nomeDoAtributo = nomeDoAtributo;
    }

    public String getMessage(){ // metodo responsavel por pegar a mensagem do error
        return String.format("O atributo %s est√° vazio", this.nomeDoAtributo);
    }
}
```